---
- hosts: all
  sudo: yes

  pre_tasks:
    - name: add Google public key to apt
      apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        state: present

    - name: add Google to apt-get repositories
      apt_repository:
        repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'
        state: present

    - name: import the NodeSource GPG key into apt
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: add NodeSource deb repository
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main'
        state: present

    - name: add NodeSource deb-src repository
      apt_repository:
        repo: 'deb-src https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main'
        state: present

    - name: add NodeSource repository preferences
      copy:
        src: files/deb_nodesource_com_node.pref
        dest: /etc/apt/preferences.d/deb_nodesource_com_node.pref

    - apt: "name={{ item }} state=installed update_cache=yes"
      with_items:
        - dbus-x11
        - default-jre
        - firefox
        - git
        - google-chrome-stable
        - nodejs
        - python
        - xvfb

  tasks:
    - name: symlink /user/bin/nodejs to /usr/bin/node
      file:
        src: /usr/bin/nodejs
        dest: /usr/bin/node
        state: link

    - name: install bower
      command: npm install -g bower

    - name: install web-component-tester
      command: npm install -g web-component-tester

    - name: copy xvfb init script to /etc/init.d
      copy:
        src: files/xvfb
        dest: /etc/init.d/xvfb
        mode: 0770

    - name: Start xvfb service
      service:
        name: xvfb
        state: started
