---
- hosts: all
  become: yes
  vars:
    firefox_version: 46.0

  pre_tasks:
    - name: install python2
      raw: sudo apt-get -y install python-simplejson

  tasks:
    - name: add Google public key to apt
      apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        state: present

    - name: add Google to apt-get repositories
      apt_repository:
        repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'
        state: present

    - name: Add Nodesource apt key
      apt_key:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
        id: "68576280"
        state: present

    - name: add NodeSource deb repository
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main'
        state: present

    - name: add NodeSource deb-src repository
      apt_repository:
        repo: 'deb-src https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main'
        state: present

    - name: add NodeSource repository preferences
      copy:
        src: files/deb_nodesource_com_node.pref
        dest: /etc/apt/preferences.d/deb_nodesource_com_node.pref

    - apt: "name={{ item }} state=installed update_cache=yes"
      with_items:
        - dbus-x11
        - default-jre
        - git
        - google-chrome-stable
        - nodejs
        - python
        - xvfb

    - name: download Firefox
      get_url:
        url: "http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/{{ firefox_version }}/linux-x86_64/en-US/firefox-{{ firefox_version }}.tar.bz2"
        dest: "/tmp/firefox-{{ firefox_version }}.tar.bz2"
        mode: 0644

    - name: Unarchive Firefox
      unarchive:
        src: "/tmp/firefox-{{ firefox_version }}.tar.bz2"
        dest: /opt/
        copy: no

    - name: symlink /opt/firefox/firefox to /usr/bin/firefox
      file:
        src: /opt/firefox/firefox
        dest: /usr/bin/firefox
        state: link

    - name: symlink /user/bin/nodejs to /usr/bin/node
      file:
        src: /usr/bin/nodejs
        dest: /usr/bin/node
        state: link

    - name: install bower and web-component-tester via npm
      npm: "name={{ item }} global=yes"
      with_items:
        - bower
        - web-component-tester

    - name: configure bower
      copy:
        src: files/bowerrc
        dest: /root/.bowerrc
